#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell available, you may
#       want to edit this line so it runs the shell you do have.
#
#   (2) Avoid modifying this script unless you really know what you are doing.
#       It should just delegate to the Gradle wrapper executable.
#
##############################################################################

if [ "$(uname)" = Darwin ] ; then
    APP_HOME=$( cd "${0%/*}" && pwd -P )
else
    APP_HOME="$( cd "${0%/*}" && pwd -P )"
fi

app_path="${APP_HOME}/gradle/wrapper/gradle-wrapper.jar"
app_base_name=`basename "$0"`

# Add a user-defined CLASSPATH variable here if needed:
# CLASSPATH="$APP_HOME/lib/dependency.jar"

# For Cygwin or MSYS, switch paths to Windows format before running java
if expr "$OSTYPE" : 'cygwin\|msys' > /dev/null; then
    APP_HOME=`( cd "$APP_HOME" && pwd -P | sed 's|.|//&|g' )`
    APP_BASE_NAME=`basename "$1" | sed 's|.[^.]*$||'`
    APP_PATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
fi

exec "$JAVACMD" "$@" -jar "$app_path" "$@"
